# Generated by Django 6.0.6 on 2026-06-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
